XYZ/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from closends.views import exceptions

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^closends/', include('closends.urls', namespace='closends')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG is False:
    handler404 = exceptions.page_not_found
    handler500 = exceptions.page_error

closends/urls.py
from .views import *
from django.conf.urls import url, include

setting_patterns = [
    url(r'index$', person_info.user_info, name='setting_index'),

    # personal info
    url(r'user_info$', person_info.user_info, name='user_info'),
    url(r'user_info/set_head_image$', person_info.set_head_image, name='set_head_image'),
    url(r'user_info/update_username$', person_info.update_username, name='update_username'),

    url(r'user_binding$', user_binding.user_binding, name='user_binding'),

    # weibo binding
    url(r'user_binding/query_weibo_user$', user_binding.query_weibo_user, name='query_weibo_user'),
    url(r'user_binding/weibo_binding$', user_binding.weibo_binding, name='weibo_binding'),
    url(r'user_binding/weibo_unbinding$', user_binding.weibo_unbinding, name='weibo_unbinding'),
    url(r'user_binding/query_bound_weibo_info$', user_binding.query_bound_weibo_info, name='query_bound_weibo_info'),

    # zhihu binding
    url(r'user_binding/query_zhihu_user$', user_binding.query_zhihu_user, name='query_zhihu_user'),
    url(r'user_binding/zhihu_binding$', user_binding.zhihu_binding, name='zhihu_binding'),
    url(r'user_binding/zhihu_unbinding$', user_binding.zhihu_unbinding, name='zhihu_unbinding'),
    url(r'user_binding/query_bound_zhihu_info$', user_binding.query_bound_zhihu_info, name='query_bound_zhihu_info'),

    # tieba binding
    url(r'user_binding/query_tieba_user$', user_binding.query_tieba_user, name='query_tieba_user'),
    url(r'user_binding/tieba_binding$', user_binding.tieba_binding, name='tieba_binding'),
    url(r'user_binding/tieba_unbinding$', user_binding.tieba_unbinding, name='tieba_unbinding'),
    url(r'user_binding/query_bound_tieba_info$', user_binding.query_bound_tieba_info, name='query_bound_tieba_info'),

    # group manage
    url(r'friend_manage$', friend_manage.friend_manage, name='friend_manage'),
    url(r'friend_manage/add_group$', friend_manage.add_group, name='add_group'),
    url(r'friend_manage/delete_group$', friend_manage.delete_group, name='delete_group'),
    url(r'friend_manage/get_group_friends/(?:group-(?P<group>\d+))/(?:page-(?P<page>\d+)/)$', friend_manage.get_group_friends, name='get_group_friends'),

    # friend manage
    url(r'friend_manage/add_friend$', friend_manage.add_friend, name='add_friend'),
    url(r'friend_manage/delete_friend$', friend_manage.delete_friend, name='delete_friend'),
    url(r'friend_manage/add_friend_info$', friend_manage.add_friend_info, name='add_friend_info'),
    url(r'friend_manage/query_friend_info$', friend_manage.query_friend_info, name='query_friend_info'),
    url(r'friend_manage/update_friend_info$', friend_manage.update_friend_info, name='update_friend_info'),

    # weibo accounts manage
    url(r'friend_manage/delete_friend_weibo$', friend_manage.delete_friend_weibo, name='delete_friend_weibo'),
    url(r'friend_manage/add_found_friend_weibo$', friend_manage.add_found_friend_weibo, name='add_found_friend_weibo'),
    url(r'friend_manage/query_exist_friend_weibo$', friend_manage.query_exist_friend_weibo, name='query_exist_friend_weibo'),

    # zhihu accounts manage
    url(r'friend_manage/delete_friend_zhihu$', friend_manage.delete_friend_zhihu, name='delete_friend_zhihu'),
    url(r'friend_manage/add_found_friend_zhihu$', friend_manage.add_found_friend_zhihu, name='add_found_friend_zhihu'),
    url(r'friend_manage/query_exist_friend_zhihu$', friend_manage.query_exist_friend_zhihu, name='query_exist_friend_zhihu'),

    # tieba accounts manage
    url(r'friend_manage/delete_friend_tieba$', friend_manage.delete_friend_tieba, name='delete_friend_tieba'),
    url(r'friend_manage/add_found_friend_tieba$', friend_manage.add_found_friend_tieba, name='add_found_friend_tieba'),
    url(r'friend_manage/query_exist_friend_tieba$', friend_manage.query_exist_friend_tieba, name='query_exist_friend_tieba'),

]

content_patterns = [
    url(r'query_all/(?:page-(?P<page>\d+)/)$', main_page.query_all, name='index'),
    url(r'query_by_group/(?:group-(?P<group>\d+))/(?:page-(?P<page>\d+)/)$', main_page.query_by_group, name='query_by_group'),
    url(r'query_by_platform/(?P<platform>\w+)/(?:page-(?P<page>\d+)/)', main_page.query_by_platform, name='query_by_platform'),
    url(r'query_by_topic/(?:topic-(?P<topic>\w+))/(?:page-(?P<page>\d+)/)', main_page.query_by_topic, name='query_by_topic'),
]

app_name = 'closends'
urlpatterns = [
    url(r'^$', login_register.to_login, name='to_login'),
    url(r'^to_register$', login_register.to_register, name='to_register'),
    url(r'^username_login$', login_register.username_login, name='username_lgoin'),
    url(r'^email_login$', login_register.email_login, name='email_lgoin'),
    url(r'^register$', login_register.register, name='register'),
    url(r'^logout$', login_register.user_logout, name='logout'),

    url(r'^index/', include(content_patterns, namespace='content')),
    url(r'^setting/', include(setting_patterns, namespace='setting')),
    url(r'^friend_index/(?P<friend>\w+)/(?:page-(?P<page>\d+)/)$', friend_index.friend_index, name='friend_index'),
]

closends/views/exceptions.py
from django.shortcuts import render_to_response
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def page_not_found(request):
    return render_to_response('404.html')


@csrf_exempt
def page_error(request):
    return render_to_response('500.html')

closends/views/friend_index.py
import operator
from django.shortcuts import render
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

from closends.methods.draw_bar import draw_bar
from closends.methods.draw_line import draw_liveness
from closends.methods.word2cloud import generate_cloud


@csrf_exempt
@login_required
def friend_index(request, friend, page=1):
    user = request.user.userinfo
    friend_item = user.friend_set.filter(nickname=friend)[0]

    weibo_contents = friend_item.weibocontent_set.all()
    zhihu_contents = friend_item.zhihucontent_set.all()
    tieba_contents = friend_item.tiebacontent_set.all()
    all_contents = []
    all_contents += weibo_contents
    all_contents += zhihu_contents
    all_contents += tieba_contents
    all_contents.sort(key=lambda content: content.pub_date, reverse=True)

    word_num = {}
    for content in all_contents:
        topic = content.topic
        if not word_num.get(topic):
            word_num[topic] = 1
        else:
            word_num[topic] += 1
    word_num = sorted(word_num.items(), key=operator.itemgetter(1, 0), reverse=True)

    draw_bar(word_num)
    generate_cloud(word_num)
    draw_liveness(weibo_contents, zhihu_contents, tieba_contents)

    paginator = Paginator(all_contents, 20)
    try:
        contents = paginator.page(page)
    except PageNotAnInteger:
        contents = paginator.page(1)
    except EmptyPage:
        contents = paginator.page(paginator.num_pages)

    result = {'contents': contents,
              'friend': friend_item,
              'current_friend': friend, }
    return render(request, 'closends/friend_index.html', result)

closends/views/friend_manage.py
import json
from django.core.cache import cache
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.shortcuts import render, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from ..tasks import weibo_spider_friend, zhihu_spider_friend, tieba_spider_friend

"""
    好友管理模块:
        分组管理 增、移
        好友管理 增、删、改、查询
        好友账号管理 增、删、改、查询
"""


@csrf_exempt
@login_required
def friend_manage(request):
    user = request.user.userinfo
    all_friends = user.friend_set.filter(group='未分组')
    paginator = Paginator(all_friends, 9)
    friends = paginator.page(1)

    group_list = user.group_list.split(',')
    group_list = list(enumerate(group_list))
    context = {'group_list': group_list, 'current_group': 0, 'friends': friends}
    return render(request, 'closends/setting_friends_manage.html', context)


@csrf_exempt
@login_required
def get_group_friends(request, group, page):
    user = request.user.userinfo
    group_list = user.group_list.split(',')
    all_friends = user.friend_set.filter(group=group_list[int(group)])
    paginator = Paginator(all_friends, 9)
    try:
        friends = paginator.page(page)
    except PageNotAnInteger:
        friends = paginator.page(1)
    except EmptyPage:
        friends = paginator.page(paginator.num_pages)

    group_list = list(enumerate(group_list))
    context = {'group_list': group_list, 'current_group': int(group), 'friends': friends}
    return render(request, 'closends/setting_friends_manage.html', context)


@csrf_exempt
@login_required
def add_group(request):
    if request.method == 'POST':
        user = request.user.userinfo
        group_name = request.POST['group_name']
        group_list = user.group_list.split(',')
        if group_name in group_list:
            result = {'status': 'error', 'error_msg': 'group_exsit'}
            return HttpResponse(json.dumps(result), content_type='application/json')

        group_list.append(group_name)
        user.group_list = ','.join(group_list)
        user.save()
        result = {'status': 'success'}
        return HttpResponse(json.dumps(result), content_type='application/json')


@csrf_exempt
@login_required
def delete_group(request):
    if request.method == 'POST':
        user = request.user.userinfo
        group_list = user.group_list.split(',')
        group_name = request.POST['group_name']
        group_list.remove(group_name)
        user.group_list = ','.join(group_list)
        user.save()

        friends = user.friend_set.filter(group=group_name)
        for friend in friends:
            friend.group = '未分组'
            friend.save()
        return HttpResponse("")


@csrf_exempt
@login_required
def add_friend(request):
    user = request.user.userinfo
    group_list = user.group_list.split(',')
    return render(request, 'closends/setting_add_friends.html', {'group_list': group_list})


@csrf_exempt
@login_required
def delete_friend(request):
    if request.method == "POST":
        user = request.user.userinfo
        friend = user.friend_set.filter(nickname=request.POST['friend_name'])[0]
        friend.delete()
        return HttpResponse("")


@csrf_exempt
@login_required
def add_friend_info(request):
    if request.method == 'POST':
        user = request.user.userinfo
        nickname = request.POST['nickname']
        group_name = request.POST['group']
        if user.friend_set.filter(nickname=nickname):
            result = {'status': 'error', 'error_msg': 'nickname_exist'}
            return HttpResponse(json.dumps(result), content_type='application/json')

        if not request.FILES:
            user.friend_set.create(nickname=nickname, group=group_name)
        else:
            head_img = request.FILES['head_img']
            user.friend_set.create(nickname=nickname, head_img=head_img, group=group_name)
        user.save()
        result = {'status': 'success'}
        return HttpResponse(json.dumps(result), content_type='application/json')


@csrf_exempt
@login_required
def query_friend_info(request):
    if request.method == 'POST':
        user = request.user.userinfo
        friend_name = request.POST['friend_name']
        friend = user.friend_set.filter(nickname=friend_name)[0]
        head_img = friend.image_name()
        result = {'status': 'success',
                  'head_img': head_img,
                  'group_name': friend.group}
        return HttpResponse(json.dumps(result), content_type='application/json')


@csrf_exempt
@login_required
def update_friend_info(request):
    if request.method == 'POST':
        user = request.user.userinfo
        nickname = request.POST['nickname']
        old_nickname = request.POST['old_nickname']
        if nickname != old_nickname:
            if user.friend_set.filter(nickname=nickname):
                result = {'status': 'error', 'error_msg': 'nickname_exist'}
                return HttpResponse(json.dumps(result), content_type='application/json')

        group_name = request.POST['group']
        friend = user.friend_set.filter(nickname=old_nickname)[0]
        friend.nickname = nickname
        friend.group = group_name
        if request.FILES:
            friend.head_img = request.FILES['head_img']
        friend.save()
        result = {'status': 'success'}
        return HttpResponse(json.dumps(result), content_type='application/json')


@csrf_exempt
@login_required
def delete_friend_weibo(request):
    if request.method == 'POST':
        user = request.user.userinfo
        friend_name = request.POST['friend_name']
        friend = user.friend_set.filter(nickname=friend_name)[0]
        friend.weibo_ID = ""
        friend.weibo_account = ""
        friend.weibo_link = ""
        friend.weibo_head = ""
        friend.save()
        return HttpResponse("")


@csrf_exempt
@login_required
def add_found_friend_weibo(request):
    if request.method == 'POST':
        user = request.user.userinfo
        friend_name = request.POST['friend_name']
        friend = user.friend_set.filter(nickname=friend_name)[0]
        friend.weibo_ID = request.POST['ID']
        friend.weibo_account = request.POST['account']
        friend.weibo_link = request.POST['link']
        friend.weibo_head = request.POST['head']
        friend.weibocontent_set.all().delete()
        friend.save()

        args = {'id': friend.id, 'weibo_ID': friend.weibo_ID}
        weibo_spider_friend.delay(request.user.username, args)
        
        updating_list = cache.get_or_set('weibo_updating_list', set())
        updating_list.add(friend.id)
        cache.set('weibo_updating_list', updating_list, None)
        return HttpResponse("")


@csrf_exempt
@login_required
def query_exist_friend_weibo(request):
    if request.method == 'POST':
        user = request.user.userinfo
        friend_name = request.POST['friend_name']
        friend = user.friend_set.filter(nickname=friend_name)[0]
        account = friend.weibo_account
        link = friend.weibo_link
        head = friend.weibo_head
        result = {'account': account, 'link': link, 'head': head}
        return HttpResponse(json.dumps(result), content_type='application/json')


@csrf_exempt
@login_required
def delete_friend_zhihu(request):
    if request.method == 'POST':
        user = request.user.userinfo
        friend_name = request.POST['friend_name']
        friend = user.friend_set.filter(nickname=friend_name)[0]
        friend.zhihu_ID = ""
        friend.zhihu_account = ""
        friend.zhihu_link = ""
        friend.zhihu_head = ""
        friend.save()
        return HttpResponse("")


@csrf_exempt
@login_required
def add_found_friend_zhihu(request):
    if request.method == 'POST':
        user = request.user.userinfo
        friend_name = request.POST['friend_name']
        friend = user.friend_set.filter(nickname=friend_name)[0]
        friend.zhihu_ID = request.POST['ID']
        friend.zhihu_account = request.POST['account']
        friend.zhihu_link = 'https://www.zhihu.com' + request.POST['link']
        friend.zhihu_head = request.POST['head']
        friend.zhihucontent_set.all().delete()
        friend.save()

        args = {'id': friend.id, 'zhihu_ID': friend.zhihu_ID}
        zhihu_spider_friend.delay(request.user.username, args)

        updating_list = cache.get_or_set('zhihu_updating_list', set())
        updating_list.add(friend.id)
        cache.set('zhihu_updating_list', updating_list, None)
        return HttpResponse("")


@csrf_exempt
@login_required
def query_exist_friend_zhihu(request):
    if request.method == 'POST':
        user = request.user.userinfo
        friend_name = request.POST['friend_name']
        friend = user.friend_set.filter(nickname=friend_name)[0]
        account = friend.zhihu_account
        link = friend.zhihu_link
        head = friend.zhihu_head
        result = {'account': account, 'link': link, 'head': head}
        return HttpResponse(json.dumps(result), content_type='application/json')


@csrf_exempt
@login_required
def delete_friend_tieba(request):
    if request.method == 'POST':
        user = request.user.userinfo
        friend_name = request.POST['friend_name']
        friend = user.friend_set.filter(nickname=friend_name)[0]
        friend.tieba_ID = ""
        friend.tieba_account = ""
        friend.tieba_link = ""
        friend.tieba_head = ""
        friend.save()
        return HttpResponse("")


@csrf_exempt
@login_required
def add_found_friend_tieba(request):
    if request.method == 'POST':
        user = request.user.userinfo
        friend_name = request.POST['friend_name']
        friend = user.friend_set.filter(nickname=friend_name)[0]
        friend.tieba_ID = request.POST['ID']
        friend.tieba_account = request.POST['account']
        friend.tieba_link = request.POST['link']
        friend.tieba_head = request.POST['head']

closends/templates/closends/login.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    {% load static %}
    <title>Closends-特别的关注，送给特别的TA</title>
    <meta charset="UTF-8"/>

    <link href="{% static '/closends/img/closends.ico' %}" rel="shortcut icon">
    <link href="/static/closends/css/bootstrap.css" rel="stylesheet">
    <script src="/static/closends/js/jquery.min.js"></script>
    <script src="/static/closends/js/bootstrap.js"></script>

    <style>
        html {
            height: 100%;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }

        body {
            height: 100%;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-image: url({% static '/closends/img/login_bg.jpg' %});
            background-size: cover;
            line-height: 1.333;
        }

        .ui_icon {
            display: inline-block;
            zoom: 1
        }

        .icon_closends_logo {
            width: 251px;
            height: 98px;
            background-image: url(/static/closends/img/closends-login-logo.32.png);
        }

        .lay_main {
            color: #ffffff;
            height: 100%;
            min-height: 600px;
            z-index: 2
        }

        .lay_main .lay_head {
            top: 95px;
            width: 750px;
            margin: 0 auto;
            position: relative
        }

        .lay_main .lay_body{
            background-color: white;
            width: 25%;
            height: 40%;
            margin-left: 50%;
        }

        .lay_main .lay_body .nav{
            margin-left: 20%;
            margin-top: 5%;
        }

        .lay_main .lay_body form{
            color: black;
            width:60%;
            margin-top: 5%;
            margin-left: 20%;
        }

        .lay_main .lay_body .tab-content .checkbox{
            margin-left: 20%;
        }

        .lay_main .lay_body .tab-content .btn{
            width: 115%;
            margin-left: -8%;
            margin-top: 5%;
            background-color: #3487ff;
        }

        .lay_main .lay_body .bottom{
            margin-top: 5%;
            margin-left: 40%;
        }

        .lay_main .lay_foot {
            position: absolute;
            bottom: 5%;
            left: 0;
            width: 100%;
            z-index: 2
        }

        .lay_main .lay_foot a {
            color: white;
            text-decoration: none
        }

        .lay_main .lay_foot .copyright {
            text-align: center
        }

        .lay_main .lay_foot .copyright p {
            line-height: 24px;
            font-size: 12px;
        }
    </style>
</head>

<body>
    <div class="lay_main" id="lay">

        <div class="lay_head">
            <h1><i class="ui_icon icon_closends_logo"></i></h1>
        </div>

        <div class="lay_body container">

            <ul class="nav nav-pills">
                <li class="active"><a href="#username_login_form" data-toggle="tab">用户名登录</a></li>
                <li><a href="#email_login_form" data-toggle="tab">邮箱登录</a></li>
            </ul>

            <div class="tab-content">
                <form id="username_login_form" class="form-horizontal tab-pane active">
                    <div class="form-group">
                        <input id="username" type="text" name="username" class="form-control"  placeholder="Username" autocomplete>
                    </div>

                    <div class="form-group">
                        <input id="password" type="password" name="password" class="form-control" placeholder="Password" autocomplete>
                    </div>

                    <div class="checkbox">
                        <label><input type="checkbox" name="remember_me"> 记住密码</label>
                    </div>

                    <button id="username_login" type="button" class="btn btn-default">Submit</button>
                </form>
                <form id="email_login_form" class="form-horizontal tab-pane">
                    <div class="form-group">
                        <input id="email" type="email" name="email" class="form-control"  placeholder="Email">
                    </div>

                    <div class="form-group">
                        <input id="password" type="password" name="password" class="form-control" placeholder="Password">
                    </div>

                    <div class="checkbox">
                        <label><input type="checkbox" name="remember_me"> 记住密码</label>
                    </div>
                    <button id="email_login" type="button" class="btn btn-default">Submit</button>
                </form>
            </div>

            <div class="bottom">
                <a href="#">忘记密码</a>
                <a href="{% url 'closends:to_register' %}">注册新账号</a>
                <a href="#">意见反馈</a>
            </div>
        </div>

        <div class="lay_foot">
            <div class="lay_inner">
                <div class="copyright">
                    <p><a href="#" target="_blank">Software Engineering, School of Computer Science and Technology, Harbin Institute of Technology</a></p>
                    <p class="copyright_en">Copyright &copy; 2017 Closends - 特别的关注，送给特别的TA </p>
                    <p class="copyright_cn">Designed by <a href="http://neilyu.cn" target="_blank">Neil.YU</a> from <a
                            href="https://github.com/HITXYZ" target="_blank">XYZ</a></p>
                </div>
            </div>
        </div>
    </div>

    <script>
        let flag = {
            "username": false,
            "email": false,
            "password": false
        };

        $(document).ready(function () {
            $("#email, #username").focus(function () {
                $(this).css('border-color', 'grey');
            });

            $("#email").blur(function () {
                let email = $("#email").val();
                let pattern_email = /\b(^['_A-Za-z0-9-]+(\.['_A-Za-z0-9-]+)*@([A-Za-z0-9-])+(\.[A-Za-z0-9-]+)*((\.[A-Za-z0-9]{2,})|(\.[A-Za-z0-9]{2,}\.[A-Za-z0-9]{2,}))$)\b/;
                if (!pattern_email.test(email)) {
                    document.getElementById("mail-error").style.display = "block";
                    flag.email = false;
                } else {
                    document.getElementById("mail-error").style.display = "none";
                    flag.email = true;
                }
                if (email.length === 0) {
                    document.getElementById("mail-tips").style.display = "block";
                    flag.email = false;
                }
            });

            $("#username_login_form #password").focus(function () {
                $(this).css('border-color', 'grey');
            });

            $("#email_login_form #password").focus(function () {
                $(this).css('border-color', 'grey');
            });

            $("#password").blur(function () {
                let password = $("#password").val();
                let pattern_password = /\b(^['A-Za-z0-9]{8,16}$)\b/;
                if (!pattern_password.test(password)) {
                    document.getElementById("password-error").style.display = "block";
                    flag.password = false;
                }

                else {
                    document.getElementById("password-error").style.display = "none";
                    flag.password = true;
                }

                if (password.length === 0) {
                    document.getElementById("password-tips").style.display = "block";
                    flag.password = false;
                }
            });

            $('#username_login').on('click', function () {
                //if(flag['username'] && flag['password']){
                    let user_info = $('#username_login_form').serialize();
                    $.ajax({
                    url: "{% url 'closends:username_lgoin' %}",
                    type: "post",
                    datatype: "json",
                    data: user_info,
                    async: false,
                    success: function (ret) {
                        if (ret.status === "success")
                            window.location = '{% url 'closends:content:index' page=1%}';
                        else {
                            if(ret.error_msg === 'user_not_exist'){
                                $("#username").val("").css('border-color', 'red');
                                $("#username_login_form #password").val("");
                            }
                            else if(ret.error_msg === 'wrong_password'){
                                $("#username_login_form #password").val("").css('border-color', 'red');
                            }
                            else{
                                //pass
                            }
                        }//else
                    }//success
                })//ajax
                //}//if
            });

            $('#email_login').on('click', function () {
                //if(flag['email'] && flag['password']) {
                    let user_info = $('#email_login_form').serialize();
                    $.ajax({
                        url: "{% url 'closends:email_lgoin' %}",
                        type: "post",
                        datatype: "json",
                        data: user_info,
                        async: false,
                        success: function (ret) {
                            if (ret.status === "success")
                                window.location = '{% url 'closends:content:index' page=1%}';
                            else {
                                if (ret.error_msg === 'user_not_exist') {
                                    $("#email").val("").css('border-color', 'red');
                                    $("#email_login_form #password").val("");
                                }
                                else if (ret.error_msg === 'wrong_password') {
                                    $("#email_login_form #password").val("").css('border-color', 'red');
                                }
                                else {
                                    //pass
                                }
                            }//else
                        }//success
                    });//ajax
                //}//if
            });
        });
    </script>
</body>

</html>

closends/templates/closends/setting_base.html
{% extends 'closends/base.html' %}

{% block css_load %}
    <link href="/static/closends/css/bootstrap.css" rel="stylesheet">
    <script src="/static/closends/js/bootstrap.js"></script>
    <script src="/static/closends/js/jquery.min.js"></script>

    <style>
        .sidebar_box{
            background-color: whitesmoke;
            width: 150px;
            height: 500px;
            margin-top: 10%;
            margin-left: 10%;
        }

        .sidebar_box .setting_bar{
            margin-top: 10%;
        }

        .sidebar_box .setting_bar .btn{
            width:100%;
            background-color: lightblue;
        }
    </style>

    {% block style_load %}

    {% endblock %}
{% endblock %}

s{% block content_body %}
    <div class="container">
        <div class="row">
            <div class="col-md-2 sidebar_box">
                <div class="setting_bar text-center">用户设置</div>

                <div class="setting_bar">
                    <a href="{% url 'closends:setting:user_info' %}">
                        <button class="btn btn-default">个人信息</button>
                    </a>
                </div>
                <div class="setting_bar">
                    <a href="{% url 'closends:setting:user_binding' %}">
                        <button class="btn btn-default">账户绑定</button>
                    </a>
                </div>
                <div class="setting_bar">
                    <a href="{% url 'closends:setting:add_friend' %}">
                        <button class="btn btn-default">添加密友</button>
                    </a>
                </div>
                <div class="setting_bar">
                    <a href="{% url 'closends:setting:friend_manage' %}">
                        <button class="btn btn-default">密友管理</button>
                    </a>
                </div>

                {% block group_list %}

                {% endblock %}
            </div>

            {% block content_box %}

            {% endblock %}
        </div>
    </div>
{% endblock %}